# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-6bLkVdv56w-2G87mClCH0dWErzLq57
"""

import gradio as gr
import numpy as np
import tensorflow as tf
from PIL import Image
import os
import random
import zipfile

# Path to the images folder
image_folder = "test_images/test_images"

# List all PNG files
image_files = [os.path.join(image_folder, f) for f in os.listdir(image_folder) if f.endswith(".png")]

# Load images
images = []
for img_path in image_files:
    img = Image.open(img_path)
    images.append(img)

print(f"Loaded {len(images)} images from {image_folder}")

# -------------------------
# Load model
# -------------------------
model = tf.keras.models.load_model("best_model.keras")


IMG_SIZE = 128
image_dir = "test_images/test_images"
images = os.listdir(image_dir)

# -------------------------
# Game state
# -------------------------
MAX_ROUNDS = 10  # Set maximum rounds

state = {
    "round": 0,
    "human_correct": 0,
    "model_correct": 0,
    "current_label": None,
    "current_image": None,
    "game_over": False
}

# -------------------------
# Preprocessing
# -------------------------
def preprocess(img):
    img = img.resize((IMG_SIZE, IMG_SIZE))
    img = np.array(img) / 255.0
    return np.expand_dims(img, axis=0)

# -------------------------
# Next round
# -------------------------
def next_image():
    if state["game_over"]:
        return state["current_image"], f"Game Over! Final Round: {MAX_ROUNDS}"

    img_name = random.choice(images)
    label = 1 if "real" in img_name.lower() else 0

    img = Image.open(os.path.join(image_dir, img_name)).convert("RGB")

    state["current_label"] = label
    state["current_image"] = img
    state["round"] += 1

    return img, f"Round {state['round']}/{MAX_ROUNDS}"

# -------------------------
# User guess
# -------------------------
def make_guess(user_guess):
    try:
        if state["game_over"]:
            return "Game is over! Click 'Restart Game' to play again.", ""

        img = state["current_image"]
        true = state["current_label"]

        # Model prediction
        pred = model.predict(preprocess(img), verbose=0)[0][1]
        model_guess = int(pred >= 0.5)

        # Score update
        if user_guess == true:
            state["human_correct"] += 1
        if model_guess == true:
            state["model_correct"] += 1

        result = (
            f"✅ Correct Answer: {'Real' if true else 'AI'}\n\n"
            f"👤 Human guessed: {'Real' if user_guess else 'AI'}\n"
            f"🤖 Model guessed: {'Real' if model_guess else 'AI'} (confidence: {pred:.2f})"
        )

        score = (
            f"👤 Human Accuracy: {state['human_correct']}/{state['round']}  |  "
            f"🤖 Model Accuracy: {state['model_correct']}/{state['round']}"
        )

        # Check if game is over
        if state["round"] >= MAX_ROUNDS:
            state["game_over"] = True
            human_pct = (state['human_correct'] / MAX_ROUNDS) * 100
            model_pct = (state['model_correct'] / MAX_ROUNDS) * 100

            winner = "Human" if human_pct > model_pct else "AI Model" if model_pct > human_pct else "It's a Tie"

            result += f"\n\n🎉 GAME OVER! 🎉\n"
            result += f"Winner: {winner}!\n"
            result += f"👤 Human: {human_pct:.1f}% | 🤖 Model: {model_pct:.1f}%"

        return result, score
    except Exception as e:
        return f"Error: {str(e)}", "Error occurred"

# -------------------------
# Restart game
# -------------------------
def restart_game():
    state["round"] = 0
    state["human_correct"] = 0
    state["model_correct"] = 0
    state["game_over"] = False
    return next_image() + ("", "")  # Returns img, round_text, result, score

# -------------------------
# Gradio UI
# -------------------------
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🤖 Human vs AI Face Detector")
    gr.Markdown("Can **you** beat the neural network in 10 rounds?")

    img_display = gr.Image(label="Guess the Face")
    round_text = gr.Textbox(label="Round", interactive=False)

    with gr.Row():
        real_btn = gr.Button("Real")
        ai_btn = gr.Button("AI-Generated")

    result_box = gr.Textbox(label="Result", interactive=False, lines=6)
    score_box = gr.Textbox(label="Score", interactive=False, lines=2)

    with gr.Row():
        next_btn = gr.Button("Next Image")
        restart_btn = gr.Button("Restart Game", variant="secondary")

    demo.load(next_image, outputs=[img_display, round_text])

    next_btn.click(next_image, outputs=[img_display, round_text])
    real_btn.click(lambda: make_guess(1), outputs=[result_box, score_box])
    ai_btn.click(lambda: make_guess(0), outputs=[result_box, score_box])
    restart_btn.click(restart_game, outputs=[img_display, round_text, result_box, score_box])

demo.launch()

